import html
import re
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    HRFlowable
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from datetime import datetime
from zoneinfo import ZoneInfo

def clean_llm_text(text):
    """Cleans up raw LLM markdown, LaTeX math, and HTML tags before rendering."""
    if not text:
        return ""
    
    text = str(text)
    
    # 1. Convert LaTeX arrows & math symbols into clean plain text
    text = re.sub(r'\\rightarrow', ' → ', text)
    text = re.sub(r'\\approx', '~', text)
    text = re.sub(r'\\Box', '', text)
    text = re.sub(r'\$(.*?)\$', r'\1', text)  # Strip inline LaTeX dollar signs
    
    # 2. Clean up raw HTML list tags generated by LLMs
    text = re.sub(r'</?ul>', '', text)
    text = re.sub(r'<li>', '\n• ', text)
    text = re.sub(r'</li>', '', text)
    
    # 3. Standardize bullet symbols to prevent weird oversized dots
    text = re.sub(r'^[ \t]*[*–—][ \t]+', '• ', text, flags=re.MULTILINE)
    
    return text

def format_inline_markdown(text):
    """Escapes raw HTML and parses bold and italic markdown tags."""
    safe = html.escape(text)
    # Parse bold **text**
    safe = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', safe)
    # Parse italic *text*
    safe = re.sub(r'(?<!\*)\*(?!\*)(.*?)\*', r'<i>\1</i>', safe)
    return safe

def parse_markdown_to_pdf_elements(text, styles, total_width):
    """Parses cleaned text into styled ReportLab elements."""
    elements = []
    text = clean_llm_text(text)
    lines = text.split('\n')
    
    table_lines = []
    in_table = False
    
    for line in lines:
        line_str = line.strip()
        
        # Detect Markdown Table rows
        if '|' in line_str:
            table_lines.append(line_str)
            in_table = True
            continue
        elif in_table:
            if table_lines:
                table_elem = build_pdf_table(table_lines, styles, total_width)
                if table_elem:
                    elements.append(table_elem)
                    elements.append(Spacer(1, 8))
                table_lines = []
            in_table = False
            
        if not line_str:
            elements.append(Spacer(1, 4))
            continue
            
        # Headers (#, ##, ### or numbered headings like "1 Quick Overview")
        if line_str.startswith('# '):
            clean_txt = line_str[2:].replace('**', '')
            elements.append(Paragraph(html.escape(clean_txt), styles['CustomH1']))
        elif line_str.startswith('## '):
            clean_txt = line_str[3:].replace('**', '')
            elements.append(Paragraph(html.escape(clean_txt), styles['CustomH2']))
        elif line_str.startswith('### '):
            clean_txt = line_str[4:].replace('**', '')
            elements.append(Paragraph(html.escape(clean_txt), styles['CustomH3']))
        elif re.match(r'^\d+\s+[A-Z]', line_str) and len(line_str) < 60:
            clean_txt = line_str.replace('**', '')
            elements.append(Paragraph(html.escape(clean_txt), styles['CustomH2']))
        elif line_str.startswith('> '):
            # Tip/Quote box
            formatted = format_inline_markdown(line_str[2:])
            elements.append(Paragraph(f"<b>Tip:</b> {formatted}", styles['TipBox']))
        elif line_str.startswith('• ') or line_str.startswith('- '):
            # Clean bullet items
            bullet_txt = line_str.lstrip('•- ').strip()
            formatted = format_inline_markdown(bullet_txt)
            elements.append(Paragraph(f"<bullet>&bull;</bullet>{formatted}", styles['CleanBullet']))
        else:
            # Regular body text
            formatted = format_inline_markdown(line_str)
            elements.append(Paragraph(formatted, styles['CustomBody']))
            
    # Clean up trailing tables
    if in_table and table_lines:
        table_elem = build_pdf_table(table_lines, styles, total_width)
        if table_elem:
            elements.append(table_elem)
            elements.append(Spacer(1, 8))
            
    return elements

def build_pdf_table(table_lines, styles, total_width):
    """Builds an auto-sized, formatted ReportLab table."""
    raw_rows = []
    for line in table_lines:
        cells = [c.strip() for c in line.strip('|').split('|')]
        # Skip separator lines like |---|---|
        if all(re.match(r'^[:\- ]+$', c) for c in cells if c):
            continue
        raw_rows.append(cells)
        
    if not raw_rows:
        return None
        
    num_cols = max(len(row) for row in raw_rows)
    if num_cols == 0:
        return None
        
    processed_table = []
    for row_idx, row in enumerate(raw_rows):
        formatted_row = []
        while len(row) < num_cols:
            row.append("")
            
        is_header = (row_idx == 0)
        style_to_use = styles['TableHeaderText'] if is_header else styles['TableCellText']
        
        for cell in row:
            formatted_cell = format_inline_markdown(cell)
            formatted_row.append(Paragraph(formatted_cell, style_to_use))
        processed_table.append(formatted_row)
        
    col_width = total_width / num_cols
    col_widths = [col_width] * num_cols
    
    t = Table(processed_table, colWidths=col_widths)
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#1A365D")),  # Elegant Navy
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 6),
        ('TOPPADDING', (0, 0), (-1, 0), 6),
        ('BOTTOMPADDING', (0, 1), (-1, -1), 5),
        ('TOPPADDING', (0, 1), (-1, -1), 5),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.HexColor("#F7FAFC"), colors.white]),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
    ]))
    return t

def generate_travel_pdf(pdf_path, user_query, thread_id, collected):
    margin = 36  # 0.5 inch margin for better printable space
    doc = SimpleDocTemplate(
        pdf_path,
        pagesize=letter,
        rightMargin=margin,
        leftMargin=margin,
        topMargin=margin,
        bottomMargin=margin
    )
    
    usable_width = letter[0] - (margin * 2)

    # Base stylesheet setup
    styles = getSampleStyleSheet()
    
    # Custom Typography Styles
    styles.add(ParagraphStyle(name='CustomTitle', fontName='Helvetica-Bold', fontSize=22, leading=26, textColor=colors.HexColor("#1A365D"), spaceAfter=15))
    styles.add(ParagraphStyle(name='CustomH1', fontName='Helvetica-Bold', fontSize=15, leading=18, textColor=colors.HexColor("#2B6CB0"), spaceBefore=14, spaceAfter=6))
    styles.add(ParagraphStyle(name='CustomH2', fontName='Helvetica-Bold', fontSize=12, leading=15, textColor=colors.HexColor("#2D3748"), spaceBefore=10, spaceAfter=4))
    styles.add(ParagraphStyle(name='CustomH3', fontName='Helvetica-Bold', fontSize=10.5, leading=13, textColor=colors.HexColor("#4A5568"), spaceBefore=8, spaceAfter=3))
    styles.add(ParagraphStyle(name='CustomBody', fontName='Helvetica', fontSize=9, leading=13, textColor=colors.HexColor("#2D3748"), spaceAfter=4))
    styles.add(ParagraphStyle(name='CleanBullet', parent=styles['CustomBody'], leftIndent=15, firstLineIndent=-10, spaceAfter=3))
    styles.add(ParagraphStyle(name='TipBox', parent=styles['CustomBody'], backColor=colors.HexColor("#EDF2F7"), borderPadding=6, spaceBefore=4, spaceAfter=6))
    styles.add(ParagraphStyle(name='TableHeaderText', fontName='Helvetica-Bold', fontSize=8.5, leading=11, textColor=colors.white))
    styles.add(ParagraphStyle(name='TableCellText', fontName='Helvetica', fontSize=8, leading=11, textColor=colors.HexColor("#2D3748")))

    story = []

    # Title & Metadata Header
    story.append(Paragraph("AI Travel Planner Report", styles["CustomTitle"]))
    story.append(Paragraph(f"<b>User Query:</b> {html.escape(str(user_query))}", styles["CustomBody"]))
    story.append(Paragraph(f"<b>User ID:</b> {html.escape(str(thread_id))}", styles["CustomBody"]))
    
    kolkata_time = datetime.now(ZoneInfo('Asia/Kolkata'))
    story.append(Paragraph(f"<b>Generated:</b> {kolkata_time.strftime('%d %b %Y, %H:%M')} (IST)", styles["CustomBody"]))
    story.append(Spacer(1, 10))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#CBD5E0"), spaceAfter=12))

    sections = [
        ("Flight Information", collected["flight_results"]),
        ("Hotel Information", collected["hotel_results"]),
        ("Research Results", collected["research_results"]),
        ("Final Travel Plan", collected["final_response"])
    ]

    for title, text in sections:
        story.append(Paragraph(title, styles["CustomH1"]))
        parsed_elements = parse_markdown_to_pdf_elements(text, styles, usable_width)
        story.extend(parsed_elements)
        story.append(Spacer(1, 10))

    doc.build(story)
    return pdf_path